version: '3.8'

services:
  b2c-investment-platform:
    build:
      context: .
      dockerfile: Dockerfile.b2c
    container_name: b2c-investment
    ports:
      - "8502:8501"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./ml_models:/app/ml_models
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - b2c-network

  # Optional: Add a Redis service for caching
  redis:
    image: redis:7-alpine
    container_name: b2c-redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - b2c-network

  # Optional: Add a PostgreSQL service for data persistence
  postgres:
    image: postgres:15-alpine
    container_name: b2c-postgres
    environment:
      POSTGRES_DB: b2c_investment
      POSTGRES_USER: b2c_user
      POSTGRES_PASSWORD: b2c_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - b2c-network

volumes:
  redis_data:
  postgres_data:

networks:
  b2c-network:
    driver: bridge
