# Streamlit Secrets Configuration
# This file contains sensitive configuration data for the Quant Trading Service

# Kite Connect API Configuration
KITE_API_KEY = ""
KITE_API_SECRET = ""
KITE_ACCESS_TOKEN = ""

# Database Configuration
DB_FILE = "stock_data.duckdb"

# WebSocket Configuration
WEBSOCKET_HOST = "localhost"
WEBSOCKET_PORT = 8080

# Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS = "localhost:9092"
KAFKA_TOPIC = "tick-data"

# Tick Generator Configuration
TICK_RATE = 100
SYMBOLS = ["NIFTY", "BANKNIFTY", "RELIANCE", "TCS"]
DURATION = 60

# Application Configuration
APP_VERSION = "1.1.0"
APP_NAME = "Quant Trading Service" 